name: Generate ASCII Artwork
on:
  workflow_dispatch:
jobs:
  build-artwork:
    runs-on: ubuntu-latest
    steps:
    - run: |-
        # Build a message by invoking ADVICESLIP API
        curl -s https://api.adviceslip.com/advice > advice.json
        cat advice.json

        # Test to make sure the advice message has more than 5 words.
        cat advice.json | jq -r .slip.advice > advice.message
        [ $(wc -w < advice.message) -gt 5 ] && echo "Advice has more than 5 words" || (echo "Advice - $(cat advice.message)  has 5 words or less" && exit 1)

        # Deploy
        sudo apt-get install cowsay -y
        export PATH="$PATH:/usr/games:/usr/local/games"
        cat advice.message | cowsay -f $(ls /usr/share/cowsay/cows | shuf -n 1)
